function tilepath = hs3s_tile(type,root, N, E,CONT)
% Get filepath w correct filename of tile as per HydroSHEDs naming convention
% "To facilitate electronic distribution, all raster data at 3 arc-second 
% resolution have been divided into 5-degree by 5-degree tiles.The tile names
% are defined by a 7-digit identifier(N/SXXE/WXXX, XX are lat/long padded by 0)
% which refers to the latitude and longitude of the lower-left (southwest) 
% corner of the tile. For example, the coordinates of the lower-left corner
% of tile s15w065 are 15 degrees south latitude and 65 degrees west longitude."

if N<0
    NS = 's'; N = -N;
else
    NS = 'n';
end
if E<0
    WE = 'w'; E = -E;
else
    WE = 'e';
end
tilename=sprintf('%s%02d%s%03d_%s',NS,N,WE,E,type);
tilepath=fullfile(root,'data',CONT,'bil','3s',sprintf('bil%s',type),sprintf('%s_bil',tilename),sprintf('%s.bil',tilename));

%% Gernaat's original filename generator to manually apply padding - kept here to check and ensure file name correctly generated for Indus basin
% if E<10
%     if N<10
%         name = sprintf('%s\\data\\%s\\bil\\3s\\bil%s\\%s0%d%s00%d_%s_bil\\%s0%d%s00%d_%s.bil',path,CONT,type,NS,N,WE,E,type,NS,N,WE,E,type);
%         
%     else
%         name = sprintf('%s\\data\\%s\\bil\\3s\\bil%s\\%s%d%s00%d_%s_bil\\%s%d%s00%d_%s.bil',root,CONT,type, NS,N,WE,E,type, NS,N,WE,E,type);
%     end
% elseif N<13
%     if E<100
%         name = sprintf('%s\\data\\%s\\bil\\3s\\bil%s\\%s0%d%s0%d_%s_bil\\%s0%d%s0%d_%s.bil',root,CONT,type, NS,N,WE,E,type, NS,N,WE,E,type);
%     else
%         name = sprintf('%s\\data\\%s\\bil\\3s\\bil%s\\%s0%d%s%d_%s_bil\\%s0%d%s%d_%s.bil',root,CONT,type, NS,N,WE,E,type, NS,N,WE,E,type);
%     end
% elseif E<100;
%     name = sprintf('%s\\data\\%s\\bil\\3s\\bil%s\\%s%d%s0%d_%s_bil\\%s%d%s0%d_%s.bil',root,CONT,type, NS,N,WE,E,type, NS,N,WE,E,type);
% else
%     name = sprintf('%s\\data\\%s\\bil\\3s\\bil%s\\%s%d%s%d_%s_bil\\%s%d%s%d_%s.bil',root,CONT,type, NS,N,WE,E,type, NS,N,WE,E,type);
% end;
% 
% assert(strcmp(strrep(tilepath,filesep,''),strrep(strrep(name,'\',''),'/','')),'Mismatch in tilepath generated by h3s_tile, check code!')
end