%% Plots annual and monthly performance visuals

clc
clearvars
close all
addpath(genpath(fullfile(pwd,'Hydrus')))
run('myVarNames_Fut.m')

ofmatHPgenTS=fullfile(rootof,'FutScenarios_HPgen_allTS03');
ofmatHPgenTS_basintot=fullfile(rootof,'FutScenarios_HPgen_basintot03'); %w/o extension as it is added later
oxlsfile=fullfile(rootoffut,"RangeinMatrix.xlsx");
%% Load HP performance TS
pot=1; % 1=tech-tech, 4=sust-fin
currentpotname= newpots4{pot}; % pottypes2{pot};
load(strcat(ofmatHPgenTS_basintot,"_",currentpotname,".mat"),'hist_annualTS_basin','fut_annualTS_basin','cl_pfnames','cl_Qnames','LTannual_basin',...
    "hist_monTS_basin","fut_annualTS_basin", "fut_monTS_basin","LTmon_basin" )
% Convert to twh
hist_annualTS_basin=hist_annualTS_basin/1000;
fut_annualTS_basin=fut_annualTS_basin/1000;
npfs=length(cl_pfnames);
nqfs=length(cl_Qnames);
fprintf("Loaded HP annual TS for %s pot \n",currentpotname)

% Add corner name to Q
%cl_Qnames(2:end)=compose("%s: %s",[rcpcornernames rcpcornernames]' ,cl_Qnames(2:end));
cl_Qnames(2:end)=[rcpcornernames rcpcornernames]';

%% Plot annual TS absolute values for all pf in each QF
startidx=2:4:25; % for ssps
endidx=5:4:25;
figure
ci=1;
for qf=1:nqfs
    nexttile
    if qf==1
        plot(hist_annualTS_basin(:,:,qf)',"-",'DisplayName','hist')
    else
        plot(fut_annualTS_basin(:,:,qf)',"-.",'DisplayName','4cornerGCMs')
    end
    ylabel("TWh production") % from hydropower production by historical portfolio")
    xlabel("Years")
    title(cl_Qnames{qf},"Interpreter","none")
   % ylim([0.05 0.19])
end
sgtitle(sprintf("All %s portfolio ANNUAL performance under Q scenarios",currentpotname))

%% Plot annual TS for one ssp_tf corners
% NEED to check that the hist pf in the future is being loaded correctly
sspsel=3;
tfsel=2;
ssel=sspsel*1; % ssp 1-3 for near fut and 4-6 for fat fut
if tfsel==1; ssel=sspsel; else ssel=sspsel+3; end
histidx=1;

figure
sgtitle(sprintf("Performance of hist+fut pfs under hist+fut Qs for %s under %s future \n for %s potential",rcpnames{sspsel},tname{tfsel},currentpotname))

%histQ
subplot(5,1,1); hold all
%hist pf under histQ
plot(hist_annualTS_basin(histidx,:,1)','b-','DisplayName',"Histpf")
%fut 4corner pf under histQ
for pfsel=1:4
    plot(hist_annualTS_basin(sspgrps{ssel}(pfsel),:,1)','-','Color',c_ssp26(sspgrps{ssel}(pfsel),:),'DisplayName',cornernames{pfsel})
end
applymyplotformat(cl_Qnames{1})
legend
%futQs
for qsel=1:4
    subplot(5,1,1+qsel); hold all
    applymyplotformat(cl_Qnames{sspgrps{ssel}(qsel)})%,'Interpreter','none')

    %hist pf under each futQ
    plot(squeeze(fut_annualTS_basin(histidx,:,sspgrps{ssel}(pfsel))),'b--', 'DisplayName',"Histpf")
    %each fut pf under futQ-C1
    for pfsel=1:4
        plot(fut_annualTS_basin(sspgrps{ssel}(pfsel),:,sspgrps{ssel}(qsel))',"--",'Color',c_ssp26(sspgrps{ssel}(pfsel),:),'DisplayName',cornernames{pfsel})
    end
    
end

%% GOOD: Barplots with Annual stats for all Qs; 4 corner Qs in one plot, total 3ssp*2tf=6 plots
datain=LTannual_basin;
for q=1:nqfs
    seldata=[datain.min(:,:,q) datain.mean(:,:,q) datain.median(:,:,q) datain.max(:,:,q)];
    dchange(:,:,qf)=(seldata(2:end,:)-seldata(1,:))./seldata(1,:)*100;

    % Create separate plots for hist and each ssp_tf
    if q==1;
        figure;
        sgtitle(sprintf("annual energy generated by histpf and futpf under %s \n for %s potential",cl_Qnames{q},currentpotname) );
        c=0; s=0;
    elseif ismember(q,2:4:25);
        % start new figure and reset c for every 4th q
        %set(gca,'xtick',1:(npfs-1),'xticklabel',cl_pfnames(2:npfs),'ticklabelInterpreter','none')
        set(gca,'xtick',1:(npfs-1),'xticklabel',rcpcornernames,'xticklabelrotation',90,'ticklabelInterpreter','none')
        legend(["min", "mean", "median", "max"])
        c=1;        s=s+1;

        figure;subplot(4,1,c);
        sgtitle(sprintf("annual energy generated by histpf and futpf under %s \n for %s potential",tfrcpnames{s},currentpotname) );
        title(strcat(tfrcpnames{s},"_",cornernames{c}),'Interpreter','none')
    else
        c=c+1; subplot(4,1,c);
        title(strcat(tfrcpnames{s},"_",cornernames{c}),'Interpreter','none')
    end

    bar(dchange(:,:,qf))
    set(gca,'xtick',1:(npfs-1),'xticklabel',[])
    grid on
    ylabel("% change from histpf")

    xline(12.5)
end
legend(["min", "mean", "median", "max"])%%
set(gca,'xtick',1:(npfs-1),'xticklabel',rcpcornernames,'xticklabelrotation',90,'ticklabelInterpreter','none')

%% GOOD: Loop heatmap MF and FF in one
fns = ["median" "prctile10" "prctile90"]; %fieldnames(LTannual_basin);
fnnames=["Median" "10^{th} percentile" "90^{th} percentile"];
figure
for fi=1:length(fns)
    datain=squeeze(LTannual_basin.(fns(fi)))/1000;
    subplot(1,3,fi)
    imagesc(datain)
    xline(1.5,'LineWidth',1.5)
    xline(13.5,'LineWidth',1.5)
    yline(1.5,'LineWidth',1.5)
    yline(13.5,'LineWidth',1.5)
    set(gca,'xtick',1:npfs,'xticklabel',histrcpcornernames,'ytick',1:npfs,'yticklabel',histrcpcornernames,'ticklabelInterpreter','none','xticklabelrotation',90)
    title(fnnames(fi))

   % colormap(viridis) - liked parula coz its brighter
    xlabel(["Discharge datasets"; sprintf('%s                                   %s',tf_full{1},tf_full{2})])
    ylabel(["Portfolios"; sprintf('%s                                   %s',tf_full{1},tf_full{2})])
    axis square
    set(gca,'YDir','normal')
    sgtitle(sprintf("annual energy for hist+futpf under hist+futQs for %s potential",currentpotname) );
caxis([92 177])

    % Find r,c for best pf for each Q
    [~,R_forPmax]=max(datain,[],1);  % returns max for each column in input matrix
    [~,C_forQmax]=max(datain,[],2);
    [~,R_forPmin]=min(datain,[],1);  % returns max for each column in input matrix
    [~,C_forQmin]=min(datain,[],2);

    hold all
    l(1)=scatter(1:nqfs,R_forPmax,"r*",'DisplayName',"Best portfolio for each discharge");
    l(2)=scatter(1:nqfs,R_forPmin,20,"k*",'DisplayName',"Worst portfolio for each discharge");
    l(3)=scatter(C_forQmax,1:nqfs,"ro",'DisplayName',"Best discharge scenario for each portfolio");
    l(4)=scatter(C_forQmin,1:nqfs,"ko",'DisplayName',"Worst discharge scenario for each portfolio");
end
legend(l,'Location','northoutside')
mycbar("Annual energy generation in TWh/year");

%% GOOD: FOR TRYs Loop heatmap total generation MF and FF separate from historical pf under historical qf
fns = ["median" "prctile10" "prctile90"]; %fieldnames(LTannual_basin);
fnnames=[fns(1) "10^{th} percentile" "90^{th} percentile"];

tfidx=[1:13; 1 14:25];
figure
for fi=1:length(fns)
    for futtf=1:2
        datatmp=squeeze(LTannual_basin.(fns(fi)))/1000;
        datain=datatmp(tfidx(futtf,:),tfidx(futtf,:));
        subplot(2,3,(futtf-1)*3+fi)
        imagesc(datain)
        xline([1.5, 5.5,9.5])%,'LineWidth',1.5)
        yline([1.5, 5.5,9.5])%,'LineWidth',1.5)

        set(gca,'xtick',1:npfs,'xticklabel',histrcpcornernames,'ytick',1:npfs,...
            'yticklabel',histrcpcornernames,'ticklabelInterpreter','none')%,'xticklabelrotation',90)
        set(gca,'YDir','normal')
        title(fnnames(fi))

        colormap(flipud(parula)) %- liked parula coz its brighter
        xlabel(["Discharge datasets"])%; tf_full{futtf}])
        if fi==1
        ylabel([tf_full{futtf};"Portfolios"])
        end
        axis square
        colorbar
        %caxis([92 177])

        % Find r,c for best pf for each Q
        [~,R_forPmax]=max(datain,[],1);  % returns max for each column in input matrix
        [~,C_forQmax]=max(datain,[],2);
        [~,R_forPmin]=min(datain,[],1);  % returns max for each column in input matrix
        [~,C_forQmin]=min(datain,[],2);

        % save ridx for best and worst pf for full matrix size
        bestpf_idx(futtf,:,fi)=tfidx(futtf,R_forPmax);
        worstpf_idx(futtf,:,fi)=tfidx(futtf,R_forPmin);

        hold all
        l(1)=scatter(1:13,R_forPmax,"ro",'DisplayName',"Best portfolio for each discharge");
        l(2)=scatter(1:13,R_forPmin,20,"ko",'DisplayName',"Worst portfolio for each discharge");
        %l(3)=scatter(C_forPmax,1:13,"r^",'DisplayName',"Best discharge scenario for each portfolio");
        %l(4)=scatter(C_forPmin,1:13,"k^",'DisplayName',"Worst discharge scenario for each portfolio");
    end
end
sgtitle(sprintf("annual energy for hist+futpf under hist+futQs for %s potential",currentpotname) );
legend(l,'Location','northoutside')%,'NumColumns',2)
mycbar("Annual energy generation in TWh/year");

%% GOOD: CLEAN Loop heatmap total generation MF and FF separate from historical pf under historical qf
fns = ["mean" "prctile10" "prctile90"]; %fieldnames(LTannual_basin);
fnnames=["Mean" "10^{th} percentile" "90^{th} percentile"];
tfidx=[1:13; 1 14:25];
myr=1;
minmaxmat_total= table(histrcpcornernames(1:13)','VariableNames',{'pfnames'});
figure
for fi=1:length(fns)
    for futtf=1:2
        datatmp=squeeze(LTannual_basin.(fns(fi)))/1000;
        datain=datatmp(tfidx(futtf,:),tfidx(futtf,:));
        subplot(2,3,(futtf-1)*3+fi)
        imagesc(datain)
        xline([1.5, 5.5,9.5])%,'LineWidth',1.5)
        yline([1.5, 5.5,9.5])%,'LineWidth',1.5)

        set(gca,'xtick',1:npfs,'xticklabel',histrcpcornernames,'ytick',1:npfs,...
            'yticklabel',histrcpcornernames,'ticklabelInterpreter','none')%,'xticklabelrotation',90)
        set(gca,'YDir','normal')
        title(fnnames(fi))

        colormap(flipud(parula)) %- liked parula coz its brighter
        xlabel(["Discharge datasets"])%; tf_full{futtf}])
        if fi==1
        ylabel([tf_full{futtf};"Portfolios"])
        end
        axis square
        colorbar
        caxis([71 140]) % for sustpot

        % Find r,c for best pf for each Q
        [~,R_forPmax]=max(datain,[],1);  % returns max for each column in input matrix
        [~,C_forQmax]=max(datain,[],2);
        [~,R_forPmin]=min(datain,[],1);  % returns max for each column in input matrix
        [~,C_forQmin]=min(datain,[],2);

        % save ridx for best and worst pf for full matrix size
        bestpf_idx(futtf,:,fi)=tfidx(futtf,R_forPmax);
        worstpf_idx(futtf,:,fi)=tfidx(futtf,R_forPmin);

        hold all
        l(1)=scatter(1:13,R_forPmax,"ro",'DisplayName',"Best portfolio for each discharge");
        l(2)=scatter(1:13,R_forPmin,20,"ko",'DisplayName',"Worst portfolio for each discharge");
        %l(3)=scatter(C_forPmax,1:13,"r^",'DisplayName',"Best discharge scenario for each portfolio");
        %l(4)=scatter(C_forPmin,1:13,"k^",'DisplayName',"Worst discharge scenario for each portfolio");
    end
      % get min max for each pf  
        minmaxmat_total.(strcat(tf_full{futtf},"_",fns(fi)))= [min(datain,[],2), max(datain,[],2)];

end
sgtitle(sprintf("annual energy for hist+futpf under hist+futQs for %s potential",currentpotname) );
legend(l,'Location','northoutside')%,'NumColumns',2)
mycbar("Annual energy generation in TWh/year");

%% GOOD: Matrix only std
fns = ["std"]; %fieldnames(LTannual_basin);
fnnames=["Standard Deviation"];

tfidx=[1:13; 1 14:25];
figure
for fi=1:length(fns)
    for futtf=1:2
        datatmp=squeeze(LTannual_basin.(fns(fi)))/1000;
        datain=datatmp(tfidx(futtf,:),tfidx(futtf,:));
        subplot(2,1,(futtf-1)*1+fi)
        imagesc(datain)
        xline([1.5, 5.5,9.5])%,'LineWidth',1.5)
        yline([1.5, 5.5,9.5])%,'LineWidth',1.5)

        set(gca,'xtick',1:npfs,'xticklabel',histrcpcornernames,'ytick',1:npfs,...
            'yticklabel',histrcpcornernames,'ticklabelInterpreter','none')%,'xticklabelrotation',90)
        set(gca,'YDir','normal')
        title(fnnames(fi))

        colormap(flipud(parula)) %- liked parula coz its brighter
        xlabel(["Discharge datasets"])%; tf_full{futtf}])
        if fi==1
        ylabel([tf_full{futtf};"Portfolios"])
        end
        axis square
       % colorbar
        caxis([4.7 15.6])

        % Find r,c for best pf for each Q
        [~,R_forPmax]=max(datain,[],1);  % returns max for each column in input matrix
        [~,C_forQmax]=max(datain,[],2);
        [~,R_forPmin]=min(datain,[],1);  % returns max for each column in input matrix
        [~,C_forQmin]=min(datain,[],2);

        % save ridx for best and worst pf for full matrix size
        bestpf_idx(futtf,:,fi)=tfidx(futtf,R_forPmax);
        worstpf_idx(futtf,:,fi)=tfidx(futtf,R_forPmin);

        hold all
        l(1)=scatter(1:13,R_forPmax,"ro",'DisplayName',"Highest SD portfolio for each discharge");
        l(2)=scatter(1:13,R_forPmin,20,"ko",'DisplayName',"Lowest SD portfolio for each discharge");
        %l(3)=scatter(C_forPmax,1:13,"r^",'DisplayName',"Best discharge scenario for each portfolio");
        %l(4)=scatter(C_forPmin,1:13,"k^",'DisplayName',"Worst discharge scenario for each portfolio");
    end
end
sgtitle(sprintf("annual energy for hist+futpf under hist+futQs for %s potential",currentpotname) );
legend(l,'Location','northoutside')%,'NumColumns',2)
mycbar("Annual energy generation in TWh/year");
%% GOOD: Loop heatmap % change in total generation MF and FF separate from historical pf under historical qf
fns = ["mean" "prctile10" "prctile90"]; %fieldnames(LTannual_basin);
fnnames=["Mean" "10^{th} percentile" "90^{th} percentile"];
tfidx=[1:13; 1 14:25];
myr=1;
minmaxmat_prct= table(histrcpcornernames(1:13)','VariableNames',{'pfnames'});

figure
for fi=1:length(fns)
    for futtf=1:2
        datatmp=squeeze(LTannual_basin.(fns(fi)))/1000;
        datatmp2=datatmp(tfidx(futtf,:),tfidx(futtf,:));
        datain=(datatmp2-datatmp2(1,1) )./datatmp2(1,:)*100; % prct change evaluated relative to histpf under each scenario
        subplot(2,3,(futtf-1)*3+fi)
        imagesc(datain) %>0)
        xline([1.5, 5.5,9.5])%,'LineWidth',1.5)
        yline([1.5, 5.5,9.5])%,'LineWidth',1.5)

        set(gca,'xtick',1:npfs,'xticklabel',histrcpcornernames,'ytick',1:npfs,...
            'yticklabel',histrcpcornernames,'ticklabelInterpreter','none')%,'xticklabelrotation',90)
        set(gca,'YDir','normal')
        title(fnnames(fi))

        colormap(flipud(parula)) %- liked parula coz its brighter
        xlabel(["Discharge datasets"])%; tf_full{futtf}])
        if fi==1
        ylabel([tf_full{futtf};"Portfolios"])
        end
        axis square        
       %caxis([-18.8 44.5]);  
       mycbar("% change in energy generation");
        % Find r,c for best pf for each Q
        [~,R_forPmax]=max(datain,[],1);  % returns max for each column in input matrix
        [~,C_forQmax]=max(datain,[],2);
        [~,R_forPmin]=min(datain,[],1);  % returns max for each column in input matrix
        [~,C_forQmin]=min(datain,[],2);

        % save ridx for best and worst pf for full matrix size
        bestpf_idx(futtf,:,fi)=tfidx(futtf,R_forPmax);
        worstpf_idx(futtf,:,fi)=tfidx(futtf,R_forPmin);

        hold all
        l(1)=scatter(1:13,R_forPmax,"ro",'DisplayName',"Best portfolio for each discharge");
        l(2)=scatter(1:13,R_forPmin,20,"ko",'DisplayName',"Worst portfolio for each discharge");
        %l(3)=scatter(C_forPmax,1:13,"r^",'DisplayName',"Best discharge scenario for each portfolio");
        %l(4)=scatter(C_forPmin,1:13,"k^",'DisplayName',"Worst discharge scenario for each portfolio");
    
    % get min max for each subplot
    changeinannualHP_meanminmax(myr,:)=[mean(datain,'all') min(datain,[],'all') max(datain,[],'all')];

    % PF wise min max for % change in mean annual performance - only future pfs      
    count_prcthighpf(myr)=sum(datain(2:end,:)>0,"all")/numel(datain(2:end,:))*100;
    fprintf("Num of pfs w vals higher than hist in %s_%s scn: %0.1f %% \n", fnnames(fi),currentpotname,count_prcthighpf(myr))  
    fprintf("Mean of change in fut %0.1f  %% \n",mean(datain(2:end,:),'all'))
    minmaxmat_prct.(strcat(tf_full{futtf},"_",fns(fi)))= [min(datain,[],2), max(datain,[],2)];       
    myr=myr+1;

    end

end
sgtitle(sprintf("annual energy for hist+futpf under hist+futQs for %s potential",currentpotname) );
legend(l,'Location','northoutside')%,'NumColumns',2)
mycbar("% change from energy generation in histpf");
disp("mean min max in the plots first means then percentiles:")
disp(changeinannualHP_meanminmax)

%% Save matrix ranges to excel
writetable(minmaxmat_total,oxlsfile,'Sheet',strcat("totals_", currentpotname))
writetable(minmaxmat_prct,oxlsfile,'Sheet',strcat("prctchange_", currentpotname))
disp("written min max matrix to xls")

%% Envelope: Plot annual TS for ssp245 corners
ssel=3; % ssp 1-3 for near fut and 4-6 for fat fut
histidx=1;
c_ssp2=[c_ssp26; c_ssp26]; % repeat for near and far fut
figure; hold all
%hist pf under histQ
l(1)=plot(hist_annualTS_basin(histidx,:,1)','b-','DisplayName','Hist_pf under Hist_Q')      ;
%hist pf 4 underfutQ
l(2)=plotEnvelopeMinMaxMean(squeeze(fut_annualTS_basin(histidx,:,sspgrps{ssel})),[0 0 1],0,1:size(fut_annualTS_basin,2));
%fut 4corner pf under histQ
l(3)=plotEnvelopeMinMaxMean(hist_annualTS_basin(sspgrps{ssel},:,1)',[0 1 0],0,1:size(hist_annualTS_basin,2));

for qsel=1:4
    %fut pf under futQ-C1-c4
    l(3+qsel)=plotEnvelopeMinMaxMean(fut_annualTS_basin(sspgrps{ssel},:,sspgrps{ssel}(qsel))',c_ssp2(sspgrps{ssel}(pfsel),:),0,1:size(fut_annualTS_basin,2));
end
xlim([0 30])
legend(l,{'Hist_pf under Hist_Q', 'Hist_pf under Fut_Qs', 'Fut_pfs under Hist_Q', 'Fut_pfs under Fut_Qs'},'Interpreter','none')


%% GOOD: simple lineplots MONT for best case pf
selqf=[1:13; 1 14:25];
figure;
for seltf=1:2
    bestpf=bestpf_idx(seltf,1,1);
    worstpf=worstpf_idx(seltf,1,1);

    fprintf("Best %s pf is for scen %s with GCM name %s\n", currentpotname, histrcpcornernames(bestpf), cl_pfnames(bestpf))
    fprintf("Worst %s pf is for scen %s with GCM name %s\n",currentpotname, histrcpcornernames(worstpf), cl_pfnames(worstpf))
    
    subplot(1,3,seltf);hold on
    %best pf
    plot(squeeze(LTmon_basin.median(bestpf,:,selqf(seltf,:)))/1000,'LineWidth',1.5)
    %histpf
    plot(squeeze(LTmon_basin.median(1,:,selqf(seltf,:)))/1000,'--','LineWidth',1.5)
    %worst pf
    plot(squeeze(LTmon_basin.median(worstpf,:,selqf(seltf,:)))/1000,':')
    ylabel("TWh")
    %       ylim([-5 25])
    grid on
    colororder(c_ssp26(1:13,:)) %'BoxStyle' ,'filled'
    applymyplotformat(strcat("Under Qs for ",tf_full(seltf)))
end
sgtitle("MONTHLY Median Energy Generation: Best, historical and worst pfs ")
lgd=legend([repelem([" "],1,13*2),histrcpcornernames(selqf(seltf,:))],'NumColumns',3);
lgd.Title.String="Best    Historical   Worst                       .";

%% GOOD: Envelope lineplots MONT for best case pf - decided to not use this because
% it might appear as spread for one model when it is actually spread in
% medians across the models.
cmap=flipud(cbrewer2("Dark2",3));
selqf=[1:13; 1 14:25];
figure;
for seltf=1:2
    bestpf=bestpf_idx(seltf,1,1);
    worstpf=worstpf_idx(seltf,1,1);

    fprintf("Best %s pf is for scen %s with GCM name %s\n", currentpotname, histrcpcornernames(bestpf), cl_pfnames(bestpf))
    fprintf("Worst %s pf is for scen %s with GCM name %s\n",currentpotname, histrcpcornernames(worstpf), cl_pfnames(worstpf))
    
    subplot(1,2,seltf);hold on
    %histpf
    l(1)=plotEnvelopeMinMaxMean(squeeze(LTmon_basin.median(1,:,selqf(seltf,:)))/1000,cmap(1,:),0,1:12);
     %worst pf
    l(2)=plotEnvelopeMinMaxMean(squeeze(LTmon_basin.median(worstpf,:,selqf(seltf,:)))/1000,cmap(2,:),0,1:12);
    %best pf
    l(3)=plotEnvelopeMinMaxMean(squeeze(LTmon_basin.median(bestpf,:,selqf(seltf,:)))/1000,cmap(3,:),0,1:12);
   
    ylabel("TWh")
    %       ylim([-5 25])
    grid on
    colororder(c_ssp26(1:13,:)) %'BoxStyle' ,'filled'
    applymyplotformat(strcat("Under Qs for ",tf_full(seltf)))
end
sgtitle("MONTHLY Median Energy Generation: Best, historical and worst pfs ")
lgd=legend([" ","Historical"," ", "Worst","","Best"],'NumColumns',2,'Orientation','horizontal');
% lgd.Title.String="Historical Worst Best";
 

%% simple boxplots ANNUAL
figure;
for ssel=1:3
    for qf=1:5
        subplot(3,5,qf+(ssel-1)*5)
        if qf==1
            boxplot(hist_annualTS_basin([1 sspgrps{ssel}],:)','Symbol','.','Colors',c_ssp26(1:5,:)) %'BoxStyle' ,'filled'
            %ylabel("TWh per year")
        else
            boxplot(fut_annualTS_basin([1 sspgrps{ssel}],:,qf)','Symbol','.','Colors',c_ssp26(1:5,:))
        end
        title(strcat("Under Q for ",histrcpcornernames{qf}))
        ylim([80 175])
        grid on

    end
end
sgtitle("Annual Energy Generation in TWh per year")

%% simple boxplots MONT
figure;
for ssel=1:3
    for qf=1:5
        subplot(3,5,qf+(ssel-1)*5)
        if qf==1
            boxplot(hist_monTS_basin([1 sspgrps{ssel}],:)'/1000,'Symbol','.','Colors',c_ssp26(1:5,:)) %'BoxStyle' ,'filled'
            %ylabel("TWh per year")
        else
            boxplot(fut_monTS_basin([1 sspgrps{ssel}],:,qf)'/1000,'Symbol','.','Colors',c_ssp26(1:5,:))
        end
        title(strcat("Under Q for ",histrcpcornernames{qf}))
        ylim([-5 25])
        grid on

    end
end
sgtitle("MONTHLY Energy Generation ub TWh per year")

%% simple lineplots MONT
figure;
for ssel=1:3
    for qf=1:5
        subplot(3,5,qf+(ssel-1)*5)
        plot(LTmon_basin.median(1,:,qf)'/1000,'--','LineWidth',1.5)

        hold on
        plot(LTmon_basin.median(sspgrps{ssel},:,qf)'/1000)
        title(strcat("Under Q for ",histrcpcornernames{qf}))
        ylim([-5 25])
        grid on
        colororder(c_ssp26(1:5,:)) %'BoxStyle' ,'filled'

    end
end
sgtitle("MONTHLY Energy Generation in TWh per year")
legend(histrcpcornernames(1:5))


%% Prepare long tables for box plots
%NEED TO MAKE SURE THE VARNAMES ARE CORRECTLY assigned for 4CORNERS
% NOT LOADING ALL 4CORNERS*5PFS CORRECTLY! HIST*5PFS IS LOADED FINE
histidx=1;
compile_long= [hist_annualTS_basin(histidx,:,1)'
    reshape(fut_annualTS_basin(histidx,:,sspgrps{ssel}),30*4,1)
    reshape(hist_annualTS_basin(sspgrps{ssel},:,1)',40*4,1)
    reshape(fut_annualTS_basin(sspgrps{ssel},:,sspgrps{ssel}(qsel))',30*4,1)];

Qtype= categorical([repelem(["Q_Hist"], 40) ...
    repelem(strcat("Q_", rcpnames{ssel},"_",cornernames),30) ...
    repelem(["Q_Hist"],40*4) ...
    repelem(strcat("Q_", rcpnames{ssel},"_",cornernames),30) ]);

PFtype = categorical([repelem(["PF_Hist"], 40) ...
    repelem(["PF_Hist"], 30*4) ...
    repelem(strcat("PF_", rcpnames{ssel},"_",cornernames),40) ...
    repelem(strcat("PF_", rcpnames{ssel},"_",cornernames),30) ...
    ]);
Q_PF=compose("%s_%s",Qtype',PFtype');

tbl=table(compile_long, Qtype', PFtype',Q_PF,'VariableNames', {'TS', 'Qtype', 'PFtype','Q_PF'});
tbl=sortrows(tbl,"Q_PF");

% %%
% tbl2=table(repelem(1:nfuts,size(HPchange_cellprct_long,1))',HPchange_cellprct_long(:),repelem(["dHP"],numel(HPchange_cellprct_long))');
% tbl=[tbl1;tbl2];
% tbl.Properties.VariableNames={'FutScen', 'Val'};
%
%% boxplots group by discharges
%
figure
boxplot(tbl.TS,tbl.Q_PF,'ColorGroup',tbl.Qtype,'PlotStyle','compact', 'boxstyle','filled')%'whisker',inf,'OutlierSize',2,'Symbol','.')
%,'label',{},'orientation','horizontal',ScensComp,'orientation','horizontal','FactorDirection','list','FullFactors','off','FactorSeparator',[1]); %'FactorGap',[10 ,.1],
%% boxplots group by pf
figure
boxchart(tbl.Var1,tbl.Var2,'GroupByColor',tbl.Var3) %,'MarkerStyle','none')%'Notch','on',
xline([4.5:4:24]) % ssp splits
xline([12.5],'color','red','LineWidth',1.5) % tf splits
set(gca,'XTick',1:24,'XTickLabel',fname(2:end),'ticklabelinterpreter','none','XTickLabelRotation',90)
ylabel("% Change")
legend(["Discharge" "Theoretical potential"])
applymyplotformat('Changes in long term annual averages')
ylim([-100 200])
text([6 18],[180 180],strcat(tname,": ", tframe),'HorizontalAlignment','center','fontweight','bold')

%% Plot hist pf in all qfs _ Effect of only climate
figure
sspsel=1;
histidx=1;

sgtitle(sprintf("Hist %s portfolio under future Qs",currentpotname))
for ssel=1:3
    %histQ
    subplot(3,1,ssel)
    title(sprintf(" for %s",rcpnames{ssel}))

    hold all
    %hist pf under histQ
    plot(histyrs_ts,hist_annualTS_basin(histidx,:,1)','k-','DisplayName',"Histpf",'LineWidth',1.5)

    % plot hist pf under rcp1Qs NF and FF
    qsel=sspgrps{ssel};
    plot(nfyrs_ts,squeeze(fut_annualTS_basin(histidx,:,qsel))) %, 'DisplayName',cl_Qnames{qsel})
    qsel=sspgrps{ssel+3};
    plot(ffyrs_ts,squeeze(fut_annualTS_basin(histidx,:,qsel))) %,'b--', 'DisplayName',"Histpf")

    ylim([180 400])
    xlim([1979, 2099])
    xline([2036, 2066],'LineStyle',':')
    ylabel("TWh")
end



